name: Release Charts
on:
  push:
    branches: [main]
    paths: ["charts/**"]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: rhysmcneill/helm-semver@v1.0.1
        with:
          registry: oci://ghcr.io/${{ github.repository_owner }}/helm-charts
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          changelog: "true"